// GENERATED by tests/campaign/solve_puzzles.mjs --write (CAMPAIGN tooling): the placement that solves each puzzle in the headless sim, with the result it earns.
// Do not hand-edit: change a puzzle in puzzles.js and run the solver again; tests/campaign/puzzles.test.mjs replays every entry and fails when one stops winning.
export const SOLUTIONS = {};
