// AUTO-GENERATED by tools/gen-registry.mjs. Do not edit.
import * as m0 from '../ui/hud/announcer.js';
import * as m1 from '../ui/hud/armymeter.js';
import * as m2 from '../ui/hud/cameramodes.js';
import * as m3 from '../ui/hud/killfeed.js';
import * as m4 from '../ui/hud/mutators.js';
import * as m5 from '../ui/hud/objective.js';
import * as m6 from '../ui/hud/selection.js';
import * as m7 from '../ui/hud/speed.js';
import * as m8 from '../ui/hud/timer.js';
export const SCREEN_MODULES = {
};
export const HUD_MODULES = {
  "announcer": m0,
  "armymeter": m1,
  "cameramodes": m2,
  "killfeed": m3,
  "mutators": m4,
  "objective": m5,
  "selection": m6,
  "speed": m7,
  "timer": m8,
};
export const EDITOR_MODULES = {
};
