// AUTO-GENERATED by tools/gen-registry.mjs. Do not edit.
import * as m0 from '../ui/screens/splash.js';
import * as m1 from '../ui/screens/title.js';
import * as m2 from '../ui/hud/announcer.js';
import * as m3 from '../ui/hud/armymeter.js';
import * as m4 from '../ui/hud/bubbles.js';
import * as m5 from '../ui/hud/cameramodes.js';
import * as m6 from '../ui/hud/helpoverlay.js';
import * as m7 from '../ui/hud/killfeed.js';
import * as m8 from '../ui/hud/minimap.js';
import * as m9 from '../ui/hud/mutators.js';
import * as m10 from '../ui/hud/objective.js';
import * as m11 from '../ui/hud/orders.js';
import * as m12 from '../ui/hud/photo.js';
import * as m13 from '../ui/hud/powers.js';
import * as m14 from '../ui/hud/selection.js';
import * as m15 from '../ui/hud/speed.js';
import * as m16 from '../ui/hud/takecommand.js';
import * as m17 from '../ui/hud/teaching.js';
import * as m18 from '../ui/hud/timer.js';
import * as m19 from '../ui/hud/typecounts.js';
export const SCREEN_MODULES = {
  "splash": m0,
  "title": m1,
};
export const HUD_MODULES = {
  "announcer": m2,
  "armymeter": m3,
  "bubbles": m4,
  "cameramodes": m5,
  "helpoverlay": m6,
  "killfeed": m7,
  "minimap": m8,
  "mutators": m9,
  "objective": m10,
  "orders": m11,
  "photo": m12,
  "powers": m13,
  "selection": m14,
  "speed": m15,
  "takecommand": m16,
  "teaching": m17,
  "timer": m18,
  "typecounts": m19,
};
export const EDITOR_MODULES = {
};
