// AUTO-GENERATED by tools/gen-registry.mjs. Do not edit.
import * as m0 from '../content/era_ancient/beasts/common.js';
import * as m1 from '../content/era_ancient/beasts/fixture_rider.js';
import * as m2 from '../content/era_ancient/beasts/hum_lite.js';
import * as m3 from '../content/era_ancient/beasts/index.js';
import * as m4 from '../content/era_ancient/beasts/quad1.js';
import * as m5 from '../sim/abilities/index.js';
export const UNIT_MODEL_MODULES = {
};
export const PART_MODULES = {
};
export const BEAST_MODULES = {
  "common": m0,
  "fixture_rider": m1,
  "hum_lite": m2,
  "index": m3,
  "quad1": m4,
};
export const PROP_MODEL_MODULES = {
};
export const HUMOR_MODULES = {
};
export const CLIP_MODULES = {
};
export const ABILITY_MODULES = {
  "index": m5,
};
