// AUTO-GENERATED by tools/gen-registry.mjs. Do not edit.
import * as m0 from '../content/era_ancient/parts/backs.js';
import * as m1 from '../content/era_ancient/parts/capes.js';
import * as m2 from '../content/era_ancient/parts/faces.js';
import * as m3 from '../content/era_ancient/parts/hair.js';
import * as m4 from '../content/era_ancient/parts/helms.js';
import * as m5 from '../content/era_ancient/parts/legs.js';
import * as m6 from '../content/era_ancient/parts/offhands.js';
import * as m7 from '../content/era_ancient/parts/shoulders.js';
import * as m8 from '../content/era_ancient/parts/torsos.js';
import * as m9 from '../content/era_ancient/parts/weapons_melee.js';
import * as m10 from '../content/era_ancient/parts/weapons_ranged.js';
import * as m11 from '../content/era_ancient/parts/weapons_silly.js';
import * as m12 from '../content/era_ancient/beasts/common.js';
import * as m13 from '../content/era_ancient/beasts/fixture_rider.js';
import * as m14 from '../content/era_ancient/beasts/hum_lite.js';
import * as m15 from '../content/era_ancient/beasts/index.js';
import * as m16 from '../content/era_ancient/beasts/mounted.js';
import * as m17 from '../content/era_ancient/beasts/quad1.js';
import * as m18 from '../anim/clips/hum1_loco.js';
import * as m19 from '../anim/clips/index.js';
import * as m20 from '../anim/clips/poses.js';
import * as m21 from '../sim/abilities/index.js';
import * as m22 from '../sim/abilities/registry.js';
export const UNIT_MODEL_MODULES = {
};
export const PART_MODULES = {
  "backs": m0,
  "capes": m1,
  "faces": m2,
  "hair": m3,
  "helms": m4,
  "legs": m5,
  "offhands": m6,
  "shoulders": m7,
  "torsos": m8,
  "weapons_melee": m9,
  "weapons_ranged": m10,
  "weapons_silly": m11,
};
export const BEAST_MODULES = {
  "common": m12,
  "fixture_rider": m13,
  "hum_lite": m14,
  "index": m15,
  "mounted": m16,
  "quad1": m17,
};
export const PROP_MODEL_MODULES = {
};
export const HUMOR_MODULES = {
};
export const CLIP_MODULES = {
  "hum1_loco": m18,
  "index": m19,
  "poses": m20,
};
export const ABILITY_MODULES = {
  "index": m21,
  "registry": m22,
};
