// Generates docs/audio_coverage.md: every cue family -> real assets (ledger ids) or flagged synth, with the justification for synth-only
// families. Run: node tests/audio/gen_coverage.mjs
import fs from 'fs';
import path from 'path';
import { CUES, CUE_IDS, UI_CUES } from '../../src/audio/cues.js';
import { Catalog } from '../../src/audio/manifest.js';
import { SfxBank } from '../../src/audio/sfx.js';
import { SYNTH_REASONS } from './synth_reasons.mjs';
import { realManifest, root } from './helpers.mjs';

export function coverage() {
  const man = realManifest(), cat = new Catalog(man);
  const bank = new SfxBank({ catalog: cat, decode: async () => null, makeBuffer: () => null });
  const rows = CUE_IDS.map((id) => { const r = bank.resolve(id), c = CUES[id]; return { id, bus: c.bus, group: c.group, real: r.real, synth: r.synth, layers: c.layers ? c.layers.length : 1, c }; });
  const core = new Set(cat.sfx.filter((e) => e.core).map((e) => e.id));
  return { man, cat, rows, core };
}
/** family -> sources that trigger it: sim events (router handlers), abilities, UI helpers, foley/ambience, engine, layers (scanned from the source text) */
export function triggers() {
  const T = Object.fromEntries(CUE_IDS.map((i) => [i, new Set()]));
  const ids = new Set(CUE_IDS);
  const cues = fs.readFileSync(path.join(root, 'src/audio/cues.js'), 'utf8');
  const body = cues.slice(cues.indexOf('// ---------------------------------------------------------------- unit / arena profiles'));
  const grab = (txt, label) => { for (const m of txt.matchAll(/'([a-z0-9_]+)'/g)) if (ids.has(m[1])) T[m[1]].add(label); };
  const hs = body.split(/\n  H\.(\w+) = /); for (let i = 1; i < hs.length; i += 2) grab(hs[i + 1], 'event ' + hs[i]);
  const ab = /const ABILITY_CUES = \{([\s\S]*?)\};/.exec(body); if (ab) for (const m of ab[1].matchAll(/(\w+): '([a-z0-9_]+)'/g)) if (ids.has(m[2])) T[m[2]].add('ability ' + m[1]);
  const ai = /export function arenaInfo[\s\S]*?\n}\n/.exec(body); if (ai) grab(ai[0], 'arena ambience');
  const st = /const STEP_BY_BIOME = \{([\s\S]*?)\};/.exec(body); if (st) grab(st[1], 'foley bed (biome)');
  const tk = /tick\(dt\) \{[\s\S]*?\n    \},/.exec(body); if (tk) grab(tk[0], 'foley bed');
  for (const [k, v] of Object.entries(UI_CUES)) T[v].add('audio.ui(' + k + ')');
  for (const f of CUE_IDS) if (CUES[f].layers) for (const l of CUES[f].layers) if (l.cue && T[l.cue]) T[l.cue].add('layer of ' + f);
  const eng = fs.readFileSync(path.join(root, 'src/audio/engine.js'), 'utf8'); grab(eng.replace(/footstep\(material[\s\S]*?\n  }/, ''), 'engine');
  for (const m of ['dirt', 'grass', 'stone', 'sand', 'snow', 'mud', 'wood', 'water']) T['step_' + m].add('audio.footstep(' + m + ')');
  return T;
}
export function render() {
  const { man, cat, rows, core } = coverage();
  const real = rows.filter((r) => r.real.length), synth = rows.filter((r) => !r.real.length), three = rows.filter((r) => r.real.length >= 3);
  const used = new Set(); for (const r of rows) for (const i of r.real) used.add(i);
  const unused = cat.sfx.filter((e) => !used.has(e.id)).map((e) => e.id);
  const TR = triggers(), L = [];
  L.push('# Audio coverage matrix', '', 'Generated by `node tests/audio/gen_coverage.mjs` from `src/audio/cues.js` (family table) resolved against `assets/manifest.json` (the asset ledger). AU3: every family resolves to at least one real asset or a flagged synth recipe (`src/audio/synth.js` has a recipe for all of them).', '');
  L.push('## Summary', '');
  L.push(`- Cue families: **${rows.length}** (spec lists 113; +3 opt-in announcer voice clips \`announce_*\`).`);
  L.push(`- Families with real assets: **${real.length}** (${three.length} of them with >= 3 real variants); synth-only: **${synth.length}**.`);
  L.push(`- Ledger: ${cat.sfx.length} SFX rows, ${cat.music.length} music rows; ${[...used].length} SFX rows are used by at least one family; ${core.size} are \`core\` (embedded in the page; AU4 offline playback).`);
  L.push(`- Where a family has fewer than 3 real variants the ledger simply holds fewer files (see the "assets" column); the shuffle bag never repeats a variant back to back, and pitch jitter (+/- 5..12 %) hides the rest.`);
  L.push(`- A synth fallback is used only when no real asset exists, or every real asset failed to load (flagged \`synth\` in \`audio.diagnostics().loaded\` / \`paths\`); it is never used while a real asset is merely still loading (non-UI cues are dropped for those few ms instead).`, '');
  L.push('## Synth-only families and why', '', '| family | justification |', '|---|---|');
  for (const r of synth) L.push(`| \`${r.id}\` | ${SYNTH_REASONS[r.id] || '**MISSING JUSTIFICATION**'} |`);
  L.push('', '## All families', '', '| family | bus | source | real assets (ledger ids) | triggered by | notes |', '|---|---|---|---|---|---|');
  for (const r of rows) {
    const c = r.c, notes = [];
    if (c.layers) notes.push(`${c.layers.length} layers`);
    if (c.loop) notes.push('loop');
    if (c.spatial) notes.push(`spatial ref ${c.ref} / max ${c.maxDist} u`);
    notes.push(`prio ${c.priority}, cd ${c.cooldownMs} ms, max ${c.maxVoices}`);
    if (c.duck) notes.push(`ducks ${c.duck.bus} ${c.duck.db} dB`);
    const ids = r.real.length ? r.real.map((i) => (core.has(i) ? i + '*' : i)).join(', ') : '—';
    L.push(`| \`${r.id}\` | ${r.bus} | ${r.real.length ? 'real' + (r.real.length < 3 ? ' (' + r.real.length + ')' : '') : '**synth**'} | ${ids} | ${[...TR[r.id]].join(', ') || '**none**'} | ${notes.join('; ')} |`);
  }
  L.push('', '`*` = core asset (base64-embedded in the page, works with fetch blocked).', '');
  L.push('## Ledger rows not referenced by any family', '', unused.length ? unused.map((i) => '`' + i + '`').join(', ') : 'none', '');
  L.push('## Music', '', '| track | mood | loop | notes |', '|---|---|---|---|');
  for (const e of cat.music) L.push(`| \`${e.id}\` | ${e.moods.join('/')}${e.energy ? ' (' + e.energy + ')' : ''} | ${e.loop ? 'native loop points' : '3 s equal-power cross-fade loop' + (e.bakedFade ? ' (tail already faded in file: not faded twice)' : '')} | ${e.core ? 'core (embedded)' : 'fetched'}; tags ${e.tags.join(', ')} |`);
  L.push('', 'Offline fallback (no music file loads): `synth.js` renders a seamless stereo bed per mood (menu, editor, victory, defeat, comedy and five battle styles: heroic, eastern, dark, mythic, brass), flagged `synth` in diagnostics.', '');
  return L.join('\n');
}
if (import.meta.url === 'file://' + process.argv[1]) {
  const out = path.join(root, 'docs/audio_coverage.md'); fs.writeFileSync(out, render()); console.log('wrote ' + out);
}
