#!/usr/bin/env python3
"""Attribution lookup for raw source folders (reads meta.json written by the fetch scripts)."""
import os, json, re, html
RAW = '/home/user/voxelwars/assets/raw'
LIC = {
  'CC0': ('CC0 1.0', 'https://creativecommons.org/publicdomain/zero/1.0/'),
  'CC-BY 3.0': ('CC BY 3.0', 'https://creativecommons.org/licenses/by/3.0/'),
  'CC-BY 4.0': ('CC BY 4.0', 'https://creativecommons.org/licenses/by/4.0/'),
  'PD': ('Public Domain', 'https://creativecommons.org/publicdomain/mark/1.0/'),
}
def pick_oga_license(lics):
    for k in ('CC0', 'CC-BY 4.0', 'CC-BY 3.0'):
        if k in lics: return k
    raise ValueError('no acceptable licence in %s' % lics)

def commons_license_key(name):
    n = (name or '').lower()
    if 'cc0' in n: return 'CC0'
    if n.startswith('public domain') or n.startswith('pd'): return 'PD'
    if re.fullmatch(r'cc[ -]by[ -]4\.0.*', n): return 'CC-BY 4.0'
    if re.fullmatch(r'cc[ -]by[ -]3\.0.*', n): return 'CC-BY 3.0'
    raise ValueError('licence not accepted: ' + name)

def kenney_title(slug):
    p = os.path.join(RAW, 'kenney-' + slug, 'files', 'License.txt')
    try:
        for l in open(p, encoding='utf-8', errors='replace'):
            l = l.strip()
            if l and not l.startswith('---'): return re.sub(r'\s*\(\d+(\.\d+)*\)\s*$', '', l)
    except Exception: pass
    return slug.replace('-', ' ').title()

def attrib(rawdir):
    """-> dict(author,title,source,licenseKey,license,licenseUrl,credit)"""
    base = os.path.join(RAW, rawdir)
    if rawdir.startswith('oga-'):
        m = json.load(open(os.path.join(base, 'meta.json')))
        key = pick_oga_license(m['licenses'])
        author = m['author'] + (' (submitted by %s)' % m['submitter'] if m.get('submitter') else '')
        d = dict(author=m['author'], title=m['title'], source=m['url'], licenseKey=key, submitter=m.get('submitter'))
    elif rawdir.startswith('kenney-'):
        slug = rawdir[len('kenney-'):]
        d = dict(author='Kenney (kenney.nl)', title='Kenney ' + kenney_title(slug), source='https://kenney.nl/assets/' + slug, licenseKey='CC0')
    elif rawdir.startswith('commons-'):
        m = json.load(open(os.path.join(base, 'meta.json')))
        key = commons_license_key(m['license'])
        art = re.sub(r'\s+', ' ', m['artist']).strip() or 'Unknown (Wikimedia Commons)'
        d = dict(author=art[:120], title=m['title'].replace('File:', ''), source=m['page'], licenseKey=key)
    elif rawdir.startswith('incompetech-'):
        m = json.load(open(os.path.join(base, 'meta.json')))
        d = dict(author='Kevin MacLeod', title=m['title'], source=m['source'], licenseKey='CC-BY 4.0')
    elif rawdir == 'synth':
        d = dict(author='VOXELWARS project (generated by tools/build_sfx.py)', title='Synthesized UI beep', source='tools/build_sfx.py', licenseKey='CC0')
    else:
        raise ValueError(rawdir)
    d['license'], d['licenseUrl'] = LIC[d['licenseKey']]
    d['attributionRequired'] = d['licenseKey'].startswith('CC-BY')
    return d
