// tools/report.mjs: the verification report and the registry's generated tables (VF 3.4; owner TOOLS-VERIFY).
//
//   node tools/report.mjs                          criteria.json -> docs/verification_report_eras.md (GENERATED, do not edit)
//   node tools/report.mjs --scan                   rewrite tools/lib/criteria_manifest.json (static scan of criterion('<id>' in tests/ and tools/)
//   node tools/report.mjs --er-table               rewrite tools/lib/er_table.json from the table of docs/eras/spec/VF.md section 3.2
//   node tools/report.mjs --scan --er-table        both
//   --check        write nothing: exit 1 when the file the other flags would write differs from the committed one (manifest/table drift = gate failure;
//                  with the report: "report_fresh", the committed report equals the generator output)
//   --from <f>     criteria.json to read (default <gate dir>/criteria.json)      --out <f>   report path (default docs/verification_report_eras.md)
//   --negctl <f>   negative-control store (default next to criteria.json)         --root <d>  tree to describe (default this repository)
//   --page <f>     built page whose sha256 and size go into the build identity    --stdout    print the report instead of writing it
//   --strict       exit 1 unless every ER is PASS (release use; the default only fails on a FAIL)
//   --help
// Sections of the report: (1) summary ER x status, (2) per-ER members with assertions, seconds, engine, (3) UNVERIFIED and PANEL with reasons,
// (4) not verifiable here (docs/eras/hosted_honesty.md), (5) build identity, (6) negative controls, (7) shortfalls (docs/eras/cuts.md).
// The output is a pure function of its inputs (no clock, no machine): the same criteria.json gives the same bytes.
// exit: 0 done / fresh, 1 drift, stale report, FAIL (or any non-PASS ER with --strict), 2 usage error
import fs from 'fs';
import path from 'path';
import crypto from 'crypto';
import { fileURLToPath } from 'url';
import { ROOT, GATE_DIR } from './lib/paths.mjs';
import { parseErTable, scanManifest, stable, erCompare, readJsonSafe } from './lib/er_rollup.mjs';
import { treeHash } from './lib/snapshot.mjs';
import { fingerprint } from './lib/fingerprint.mjs';

const HELP = fs.readFileSync(fileURLToPath(import.meta.url), 'utf8').split('\n').filter((l, i, a) => a.slice(0, i + 1).every((x) => x.startsWith('//'))).map((l) => l.replace(/^\/\/ ?/, '')).join('\n');
const cell = (s) => String(s == null ? '' : s).replace(/\|/g, '\\|').replace(/\s*\n\s*/g, ' ').trim();
const sha256 = (b) => crypto.createHash('sha256').update(b).digest('hex');

/** The first table of the section "## Decided at plan time" of cuts.md, verbatim. */
export function shortfallTable(cutsMd) {
  const lines = (cutsMd || '').split('\n');
  const start = lines.findIndex((l) => /^##\s+Decided at plan time/.test(l));
  if (start < 0) return '';
  const out = [];
  for (let i = start + 1; i < lines.length && !/^##\s/.test(lines[i]); i++) if (lines[i].startsWith('|')) out.push(lines[i]);
  return out.join('\n');
}

const STATUS_ORDER = ['FAIL', 'UNVERIFIED', 'PARTIAL', 'PANEL', 'PASS'];
const statusRank = (s) => { const i = STATUS_ORDER.findIndex((x) => String(s).startsWith(x)); return i < 0 ? 9 : i; };

/**
 * @param {{doc:object, negStore:object, honesty:string, cuts:string, identity:object, erTable:object|null}} a
 * The report states the tree of the RUN. Whether the working tree is still that tree is not part of the file (the report itself lives in the tree and
 * would change its hash): the CLI prints that comparison to stderr.
 */
export function renderReport({ doc, negStore = {}, honesty = '', cuts = '', identity = {}, erTable = null }) {
  const L = [];
  const run = doc.run || {};
  const crit = doc.criteria || {};
  const ids = Object.keys(crit).sort();
  const er = doc.er || {};
  const erNames = Object.keys(er).sort(erCompare);
  const count = (f) => ids.filter((i) => f(crit[i])).length;
  L.push('<!-- GENERATED by `node tools/report.mjs` from the gate\'s criteria.json (VF 3.4). Do not edit: change the checks, rerun the gate, regenerate. -->');
  L.push('# Verification report: Medieval, Modern and Sci-Fi eras (generated)', '');
  L.push(`Run \`${run.id || '-'}\`, tier \`${(run.tiers || [run.tier]).filter(Boolean).join('+') || '-'}\`, era scope \`${run.era || '-'}\`, tree \`${run.treeHash ? run.treeHash.slice(0, 16) : '-'}\`, node ${run.node || '-'}${run.merged ? `, merged runs: ${run.merged.join(', ')}` : ''}.`);
  L.push('', `Criteria: ${ids.length} (PASS ${count((c) => c.status === 'PASS')}, FAIL ${count((c) => c.status === 'FAIL')}, UNVERIFIED ${count((c) => c.status === 'UNVERIFIED')}, PANEL ${count((c) => c.status === 'PANEL')}); the status words follow VF 3.4: a check with zero assertions, not executed, skipped, without a negative control or with an unproven one is UNVERIFIED, never PASS.`, '');

  L.push('## 1. Summary by ER', '');
  if (!erNames.length) L.push('No ER roll-up in this criteria.json (tools/lib/criteria_manifest.json and er_table.json were not available to the gate).', '');
  else {
    L.push('| ER | criterion | status | members | missing | tier | reason |', '|---|---|---|---|---|---|---|');
    for (const n of erNames) {
      const e = er[n];
      const row = erTable && erTable.rows.find((r) => r.er === n);
      L.push(`| ${n} | ${cell(row ? row.criterion : e.criterion || '')} | **${cell(e.status)}** | ${e.members.length} | ${e.missing.length} | ${cell(e.requiredTier)} | ${cell(e.reason).slice(0, 160)} |`);
    }
    L.push('');
  }

  L.push('## 2. Members per ER', '');
  const printed = new Set();
  const table = (members) => {
    L.push('| id | status | assertions | seconds | engine | negctl | file |', '|---|---|---|---|---|---|---|');
    for (const id of members) {
      const c = crit[id];
      if (!c) { L.push(`| ${cell(id)} | NOT BUILT | - | - | - | - | - |`); continue; }
      printed.add(id);
      L.push(`| ${cell(id)} | ${cell(c.status)} | ${c.assertions} | ${(+c.seconds || 0).toFixed(1)} | ${cell(c.engine || 'node')} | ${cell(c.negctl ? (c.negctl.result || 'not run') : 'none')} | ${cell(c.file || '')} |`);
    }
    L.push('');
  };
  for (const n of erNames) { if (!er[n].members.length) continue; L.push(`### ${n} (${er[n].status})`, ''); table(er[n].members); }
  const rest = ids.filter((i) => !printed.has(i));
  if (rest.length) { L.push('### Criteria without an ER roll-up', ''); table(rest); }

  L.push('## 3. UNVERIFIED and PANEL', '');
  const unv = ids.filter((i) => ['UNVERIFIED', 'PANEL', 'FAIL'].includes(crit[i].status)).sort((a, b) => statusRank(crit[a].status) - statusRank(crit[b].status) || (a < b ? -1 : 1));
  if (!unv.length) L.push('None.', '');
  else {
    L.push('| id | status | reason | ER |', '|---|---|---|---|');
    for (const id of unv) { const c = crit[id]; L.push(`| ${cell(id)} | ${cell(c.status)} | ${cell(c.reason || (c.judge ? 'judged by ' + c.judge : ''))} | ${cell([].concat(c.er || []).join(', '))} |`); }
    L.push('');
  }
  const missingAll = erNames.flatMap((n) => er[n].missing.map((m) => [n, m]));
  if (missingAll.length) {
    L.push('Required by the ER table (VF 3.2) and not built yet:', '', '| ER | member |', '|---|---|');
    for (const [n, m] of missingAll) L.push(`| ${n} | ${cell(m)} |`);
    L.push('');
  }

  L.push('## 4. Not verifiable here', '');
  L.push(honesty.trim() ? honesty.trim() : '(docs/eras/hosted_honesty.md is missing: this section must carry the template of VF 3.12.5 before a release)', '');

  L.push('## 5. Build identity', '');
  const idf = identity;
  L.push('| item | value |', '|---|---|');
  L.push(`| treeHash (the run this report describes) | \`${run.treeHash || '-'}\` |`);
  if (idf.engineHash) L.push(`| engineHash.simCore | \`${idf.engineHash.simCore}\` |`, `| engineHash.shared | \`${idf.engineHash.shared}\` |`, `| renderHash | \`${idf.renderHash}\` |`);
  for (const e of Object.keys(idf.eraHash || {}).sort()) L.push(`| eraHash(${e}) | \`${idf.eraHash[e]}\` |`);
  L.push(`| page sha256 | ${idf.page ? `\`${idf.page.sha256}\` (${idf.page.bytes} bytes, ${cell(idf.page.name)})` : 'no page given (use --page <built fragment>)'} |`, '');

  L.push('## 6. Negative controls', '');
  const keys = Object.keys(negStore).filter((k) => !k.startsWith('_')).sort();
  if (!keys.length) L.push('No `.cache/gate/negctl.json`: no negative control has been run on this machine (`node tools/negcontrols.mjs --all`).', '');
  else {
    const ctl = keys.flatMap((k) => Object.entries(negStore[k].controls || {}).map(([nc, v]) => ({ criterion: k, nc, ...v })));
    const by = (r) => ctl.filter((x) => x.result === r).length;
    L.push(`Criteria with a stored proof: ${keys.length}; controls stored: ${ctl.length} (red-as-expected ${by('red-as-expected')}, stayed-green ${by('stayed-green')}, wrong-red ${by('wrong-red')}, baseline-red ${by('baseline-red')}, other ${ctl.length - by('red-as-expected') - by('stayed-green') - by('wrong-red') - by('baseline-red')}).`, '');
    L.push('| criterion | aggregate | controls | red-as-expected |', '|---|---|---|---|');
    for (const k of keys) { const cs = Object.values(negStore[k].controls || {}); L.push(`| ${cell(k)} | ${cell(negStore[k].result)} | ${cs.length} | ${cs.filter((x) => x.result === 'red-as-expected').length} |`); }
    L.push('');
    const not = ctl.filter((x) => x.result !== 'red-as-expected');
    if (not.length) { L.push('Not red-as-expected:', ''); for (const x of not) L.push(`- ${x.nc} (${x.criterion}): ${x.result}${x.detail ? ' - ' + cell(String(x.detail).slice(0, 120)) : ''}`); L.push(''); }
  }

  L.push('## 7. Shortfalls against Ancient (copied from docs/eras/cuts.md)', '');
  const sf = shortfallTable(cuts);
  L.push(sf || '(no table found under "Decided at plan time" in docs/eras/cuts.md)', '');
  return L.join('\n');
}

function readIf(f) { try { return fs.readFileSync(f, 'utf8'); } catch { return ''; } }

async function main(argv) {
  const opt = { from: null, out: null, negctl: null, root: ROOT, page: null };
  const flags = new Set();
  for (let i = 0; i < argv.length; i++) {
    const a = argv[i];
    if (a === '--help' || a === '-h') { console.log(HELP); return 0; }
    if (['--scan', '--er-table', '--check', '--stdout', '--strict'].includes(a)) { flags.add(a.slice(2)); continue; }
    const m = /^--(from|out|negctl|root|page)(?:=(.*))?$/.exec(a);
    if (m) { opt[m[1]] = m[2] !== undefined ? m[2] : argv[++i]; if (opt[m[1]] === undefined) { console.error('missing value for ' + a); return 2; } continue; }
    console.error('unknown argument: ' + a + ' (try --help)'); return 2;
  }
  const root = path.resolve(opt.root);
  let code = 0;
  const emit = (rel, text, what) => {
    const f = path.join(root, rel);
    const cur = readIf(f);
    if (flags.has('check')) { if (cur !== text) { console.error(`DRIFT ${rel}: ${what} differs from the committed file (run: node tools/report.mjs ${what === 'manifest' ? '--scan' : '--er-table'})`); code = 1; } else console.log(`ok   ${rel} (${what} is current)`); return; }
    if (cur === text) { console.log(`same ${rel}`); return; }
    fs.mkdirSync(path.dirname(f), { recursive: true }); fs.writeFileSync(f, text); console.log(`wrote ${rel}`);
  };
  if (flags.has('scan')) { const m = await scanManifest(root); emit('tools/lib/criteria_manifest.json', stable(m), 'manifest'); }
  if (flags.has('er-table')) {
    const vf = path.join(root, 'docs/eras/spec/VF.md');
    if (!fs.existsSync(vf)) { console.error('missing docs/eras/spec/VF.md'); return 2; }
    emit('tools/lib/er_table.json', stable(parseErTable(fs.readFileSync(vf, 'utf8'))), 'er_table');
  }
  if (flags.has('scan') || flags.has('er-table')) return code;

  const from = path.resolve(opt.from || path.join(GATE_DIR, 'criteria.json'));
  const doc = readJsonSafe(from);
  if (!doc || !doc.criteria) { console.error(`cannot read ${from}: run the gate first (node tools/gate.mjs --fast) or give --from`); return 2; }
  const negStore = readJsonSafe(path.resolve(opt.negctl || path.join(path.dirname(from), 'negctl.json'))) || {};
  try { const now = treeHash(root).treeHash; if (doc.run && doc.run.treeHash && now !== doc.run.treeHash) console.error(`note: criteria.json describes tree ${doc.run.treeHash.slice(0, 12)}; the working tree is ${now.slice(0, 12)} (the generated report is part of the tree, so equality is only expected on a clean frozen tree)`); } catch { /* no tree */ }
  const identity = {};
  try { Object.assign(identity, fingerprint(root, ['ancient'])); } catch { /* not a full tree */ }
  if (opt.page) { const b = fs.readFileSync(path.resolve(opt.page)); identity.page = { sha256: sha256(b), bytes: b.length, name: path.basename(opt.page) }; }
  const text = renderReport({
    doc, negStore, honesty: readIf(path.join(root, 'docs/eras/hosted_honesty.md')), cuts: readIf(path.join(root, 'docs/eras/cuts.md')), identity,
    erTable: readJsonSafe(path.join(root, 'tools/lib/er_table.json')),
  });
  const rel = opt.out || 'docs/verification_report_eras.md';
  const outFile = path.isAbsolute(rel) ? rel : path.join(root, rel);
  if (flags.has('stdout')) process.stdout.write(text + '\n');
  else if (flags.has('check')) {
    if (readIf(outFile) !== text + '\n') { console.error(`STALE ${rel}: the committed report differs from the generator output`); code = 1; } else console.log(`ok   ${rel} equals the generator output`);
  } else { fs.mkdirSync(path.dirname(outFile), { recursive: true }); fs.writeFileSync(outFile, text + '\n'); console.log(`wrote ${rel} (${Object.keys(doc.criteria).length} criteria, ${Object.keys(doc.er || {}).length} ER rows)`); }
  const bad = Object.entries(doc.er || {}).filter(([, e]) => (flags.has('strict') ? e.status !== 'PASS' : e.status === 'FAIL'));
  if (bad.length && !flags.has('check')) { console.error(`${bad.length} ER row(s) ${flags.has('strict') ? 'not PASS' : 'FAIL'}: ${bad.map(([n, e]) => `${n}=${e.status}`).slice(0, 12).join(' ')}`); code = 1; }
  return code;
}
if (process.argv[1] && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url)) main(process.argv.slice(2)).then((c) => process.exit(c), (e) => { console.error(e.stack || e); process.exit(1); });
