# SFX selection spec.  S(id, category, 'rawdir:regex', tags, **opts)  -- see tools/build_sfx.py for options.
# rawdir = folder under assets/raw (oga-<slug>, kenney-<pack>, commons-<slug>); regex matches the path inside it.
SPEC = []
def S(id, cat, src, tags='', core=False, notes='', **opts):
    SPEC.append(dict(id=id, cat=cat, src=src, tags=[t for t in tags.split(',') if t], core=core, notes=notes, opts=opts))

K_IMP = 'kenney-impact-sounds'; K_RPG = 'kenney-rpg-audio'; K_INT = 'kenney-interface-sounds'; K_UI = 'kenney-ui-audio'
MWT = 'oga-medieval-sound-effects-weapon-textures'; MWI = 'oga-medieval-sound-effects-weapon-impacts'
SW = 'oga-20-sword-sound-effects-attacks-and-clashes'; SHB = 'oga-10-impactshield-blocks'
VEH = 'oga-fantasy-weapons-and-apparel-sfx-library'; RPG80 = 'oga-80-cc0-rpg-sfx'; CRE1 = 'oga-80-cc0-creature-sfx'; CRE2 = 'oga-80-cc0-creture-sfx-2'
BRK = 'oga-75-cc0-breaking-falling-hit-sfx'

# ---------------------------------------------------------------- blade
S('sword_slash_1', 'blade', MWT + r':Sabre Swing', 'sword,slash,swing,whoosh', peak=2, pre=0.35, post=0.45, max=0.8, hp=350)
S('sword_slash_2', 'blade', MWT + r':Katana Swing', 'sword,slash,swing,whoosh', peak=1, pre=0.35, post=0.45, max=0.8, hp=350)
S('sword_slash_3', 'blade', MWT + r':Seax Swing', 'sword,slash,swing,whoosh', peak=1, pre=0.35, post=0.45, max=0.8, hp=350)
S('sword_slash_4', 'blade', MWT + r':Dagger Swing', 'dagger,slash,swing,whoosh', peak=1, pre=0.3, post=0.4, max=0.7, hp=300)
S('axe_swing_1', 'blade', MWT + r':Axe Swing', 'axe,swing,whoosh', peak=2, pre=0.4, post=0.5, max=0.9, hp=250)
S('sword_hit_1', 'blade', SW + r':/sword\.1\.ogg', 'sword,hit,slash', core=True, max=1.2)
S('sword_hit_2', 'blade', SW + r':/sword\.3\.ogg', 'sword,hit,slash', core=True, max=1.2)
S('sword_hit_3', 'blade', SW + r':/sword\.6\.ogg', 'sword,hit,slash', max=1.2)
S('sword_hit_4', 'blade', SW + r':/sword\.9\.ogg', 'sword,hit,slash', max=1.4)
S('blade_clash_1', 'blade', SW + r':sword_clash\.1\.ogg', 'metal,clash,parry,sword', core=True, max=1.4)
S('blade_clash_2', 'blade', SW + r':sword_clash\.4\.ogg', 'metal,clash,parry,sword', max=1.4)
S('blade_clash_3', 'blade', SW + r':sword_clash\.6\.ogg', 'metal,clash,parry,sword', max=1.5)
S('blade_clash_4', 'blade', SW + r':sword_clash\.9\.ogg', 'metal,clash,parry,sword', max=1.4)
S('blade_clash_5', 'blade', VEH + r':sword-knife-clash-14', 'metal,clash,parry', max=1.2)
S('blade_parry_1', 'blade', MWI + r':Sabre Katana Blade on Blade', 'metal,parry,ring', on=0, max=1.5)
S('blade_parry_2', 'blade', MWI + r':Spear Sabre Blade on Blade', 'metal,parry,ring', on=0, max=1.5)
S('sword_draw_1', 'blade', MWT + r':Sabre Draw Fast', 'sword,draw,unsheathe', max=1.0)
S('sword_draw_2', 'blade', MWT + r':Seax Draw Fast', 'sword,draw,unsheathe', max=1.0)
S('sword_sheath_1', 'blade', MWT + r':Katana Sheath Fast', 'sword,sheathe', max=1.0)
S('axe_chop_1', 'blade', K_RPG + r':/chop\.ogg', 'axe,chop,wood', max=1.0)
S('axe_chop_2', 'blade', 'oga-tree-chop-fall-thud:chop-tree', 'axe,chop,wood', max=1.2, on=0)
S('blade_swish_1', 'blade', 'oga-swish-bamboo-stick-weapon-swhoshes:swosh-05', 'whoosh,swing,weapon', max=0.8)
S('blade_swish_2', 'blade', 'oga-swish-bamboo-stick-weapon-swhoshes:swosh-12', 'whoosh,swing,weapon', max=0.8)
S('knife_slice_1', 'blade', K_RPG + r':knifeSlice\.ogg', 'knife,slice', max=0.8)

# ---------------------------------------------------------------- shield / wood / thud
S('shield_block_1', 'shield', SHB + r':impact\.1\.ogg', 'shield,block,wood,thud', core=True, max=1.0)
S('shield_block_2', 'shield', SHB + r':impact\.3\.ogg', 'shield,block', max=1.0)
S('shield_block_3', 'shield', SHB + r':impact\.5\.ogg', 'shield,block', max=1.2)
S('shield_block_4', 'shield', SHB + r':impact\.8\.ogg', 'shield,block', max=1.0)
S('shield_bash_1', 'shield', K_IMP + r':impactPlate_heavy_000', 'shield,bash,metal', max=1.2)
S('shield_bash_2', 'shield', K_IMP + r':impactPlate_heavy_003', 'shield,bash,metal', max=1.2)
S('wood_thud_1', 'shield', K_IMP + r':impactWood_heavy_000', 'wood,thud,shield', max=1.0)
S('wood_thud_2', 'shield', K_IMP + r':impactWood_heavy_002', 'wood,thud', max=1.0)
S('wood_thud_3', 'shield', K_IMP + r':impactWood_medium_001', 'wood,thud', max=0.9)

# ---------------------------------------------------------------- pierce
S('spear_swing_1', 'pierce', MWT + r':Spear Swing', 'spear,thrust,swing,whoosh', peak=1, pre=0.3, post=0.4, max=0.7, hp=300)
S('spear_stab_3', 'pierce', K_IMP + r':impactSoft_heavy_001', 'spear,stab,flesh,soft', max=0.9)
S('javelin_throw_1', 'pierce', 'oga-swish-bamboo-stick-weapon-swhoshes:swosh-38', 'javelin,throw,whoosh', peak=0, pre=0.45, post=0.45, max=0.9, hp=60)
S('javelin_throw_2', 'pierce', 'oga-swish-bamboo-stick-weapon-swhoshes:swosh-35', 'javelin,throw,whoosh', peak=0, pre=0.5, post=0.55, max=1.05, hp=60)

# ---------------------------------------------------------------- bow
S('bow_shot_1', 'bow', MWT + r':Scythian Recurve Shoot', 'bow,arrow,shoot,twang', core=True, on=0, max=0.6, fout=0.1, hp=180)
S('bow_shot_2', 'bow', MWT + r':English Longbow Shoot', 'bow,arrow,shoot,twang', on=0, max=0.3, fout=0.08)
S('crossbow_shot_1', 'bow', MWT + r':Crossbow Shoot', 'crossbow,bolt,shoot,twang', on=0, max=0.6, fout=0.1)
S('bow_draw_1', 'bow', MWT + r':Scythian Recurve Draw', 'bow,draw,creak', max=1.6)
S('bow_nock_1', 'bow', MWT + r':English Longbow Nock', 'bow,nock', max=0.9)
S('arrow_whoosh_1', 'bow', MWT + r':Scythian Recurve Arrow Pass\.', 'arrow,whoosh,flyby', peak=0, pre=0.5, post=0.5, max=1.0)
S('arrow_whoosh_2', 'bow', MWT + r':Crossbow Bolt Pass\.', 'arrow,whoosh,flyby', peak=0, pre=0.5, post=0.5, max=1.0)
S('arrow_whoosh_3', 'bow', MWT + r':Scythian Recurve Heavy Arrow Pass\.', 'arrow,whoosh,flyby', peak=0, pre=0.5, post=0.5, max=1.0)
S('arrow_hit_flesh_1', 'bow', K_IMP + r':impactSoft_medium_001', 'arrow,hit,flesh', core=True, max=0.8)
S('arrow_hit_flesh_2', 'bow', K_IMP + r':impactSoft_medium_003', 'arrow,hit,flesh', max=0.8)
S('arrow_hit_wood_1', 'bow', K_IMP + r':impactWood_light_001', 'arrow,hit,wood,shield', core=True, max=0.7)
S('arrow_hit_wood_2', 'bow', K_IMP + r':impactWood_light_003', 'arrow,hit,wood,shield', max=0.7)

# ---------------------------------------------------------------- impact (flesh / club / mace)
S('flesh_hit_light_1', 'impact', 'oga-37-hitspunches:hit05', 'flesh,hit,light,punch', core=True, max=0.9)
S('flesh_hit_light_2', 'impact', 'oga-37-hitspunches:hit12', 'flesh,hit,light,punch', core=True, max=0.9)
S('flesh_hit_light_3', 'impact', K_IMP + r':impactPunch_medium_001', 'flesh,hit,light,punch', max=0.8)
S('flesh_hit_light_4', 'impact', K_IMP + r':impactPunch_medium_003', 'flesh,hit,light,punch', max=0.8)
S('flesh_hit_heavy_1', 'impact', K_IMP + r':impactPunch_heavy_000', 'flesh,hit,heavy,punch', core=True, max=1.0)
S('flesh_hit_heavy_2', 'impact', K_IMP + r':impactPunch_heavy_002', 'flesh,hit,heavy,punch', core=True, max=1.0)
S('flesh_hit_heavy_3', 'impact', K_IMP + r':impactPunch_heavy_004', 'flesh,hit,heavy,punch', max=1.0)
S('mace_bonk_1', 'impact', K_IMP + r':impactMetal_heavy_001', 'mace,bonk,metal,helmet', max=1.2)
S('mace_bonk_2', 'impact', K_IMP + r':impactMetal_medium_003', 'mace,bonk,metal,helmet', max=1.0)
S('club_bonk_1', 'impact', K_IMP + r':impactWood_heavy_004', 'club,bonk,wood', max=1.0)
S('club_bonk_2', 'impact', K_IMP + r':impactWood_medium_003', 'club,bonk,wood', max=0.9)
S('helmet_ping_1', 'impact', K_IMP + r':impactTin_medium_001', 'helmet,ping,metal,bonk', max=0.9)
S('flesh_slap_1', 'impact', 'oga-37-hitspunches:hit33', 'slap,flesh', max=0.8)

# ---------------------------------------------------------------- death
S('death_grunt_1', 'death', 'oga-male-dead-voice:enemy_dead_00', 'death,grunt,male,oof', core=True, max=1.0)
S('death_grunt_2', 'death', 'oga-male-dead-voice:enemy_dead_05', 'death,grunt,male', core=True, max=1.0)
S('death_grunt_3', 'death', 'oga-male-dead-voice:enemy_dead_11', 'death,grunt,male', core=True, max=1.0)
S('death_grunt_4', 'death', 'oga-male-dead-voice:enemy_dead_06', 'death,grunt,male', max=1.0)
S('death_grunt_5', 'death', 'oga-male-dead-voice:enemy_dead_09', 'death,grunt,male', max=1.2)
S('death_oof_1', 'death', 'oga-15-vocal-male-strainhurtpainjump-sounds:slightscream-03', 'death,oof,grunt,male,comic', max=1.0)
S('death_oof_2', 'death', 'oga-15-vocal-male-strainhurtpainjump-sounds:slightscream-10', 'death,oof,grunt,male,comic', max=1.0)
S('death_scream_1', 'death', 'oga-aargh-male-screams:aargh5', 'death,scream,male', max=1.4)
S('death_scream_2', 'death', 'oga-aargh-male-screams:aargh6', 'death,scream,male', max=1.5)
S('death_dying_1', 'death', 'oga-11-male-human-paindeath-sounds:die1', 'death,dying,male', max=1.5)
S('death_dying_2', 'death', 'oga-11-male-human-paindeath-sounds:die2', 'death,dying,male', max=1.5)
S('death_hurt_1', 'death', 'oga-11-male-human-paindeath-sounds:pain3', 'hurt,pain,male', max=0.9)
S('death_comic_1', 'death', 'oga-steampunk-fantasy-voices:Hero_Die_001', 'death,comic,male', max=1.6)
S('death_comic_2', 'death', 'oga-steampunk-fantasy-voices:Minion_DieImpact_001', 'death,comic,male', max=1.4)
S('death_comic_3', 'death', 'oga-steampunk-fantasy-voices:Guard_Die_001', 'death,comic,male', max=1.6)

# ---------------------------------------------------------------- voice (battle cries etc.)
S('battle_cry_1', 'voice', 'oga-proto-germanic-voices:attack_01', 'battle cry,attack,male,war cry', core=False, max=1.2)
S('battle_cry_2', 'voice', 'oga-proto-germanic-voices:attack_02', 'battle cry,attack,male,war cry', max=1.2)
S('battle_cry_3', 'voice', 'oga-proto-germanic-voices:attack_03', 'battle cry,attack,male,war cry', max=1.2)
S('battle_cry_4', 'voice', 'oga-male-gruntyelling-sounds:/3yell6\.wav', 'battle cry,yell,male', max=1.6)
S('battle_cry_5', 'voice', 'oga-male-gruntyelling-sounds:/2yell6\.wav', 'battle cry,yell,male', max=1.8)
S('war_cry_1', 'voice', 'oga-steampunk-fantasy-voices:Knight_Attack_001', 'war cry,knight,attack', max=1.2)
S('war_cry_2', 'voice', 'oga-steampunk-fantasy-voices:Hero_Attack_001', 'war cry,hero,attack', max=1.4)
S('orc_roar_2', 'voice', 'oga-orc-voice:ORC GROWL 2', 'roar,orc,growl', max=1.8)
S('grunt_effort_1', 'voice', 'oga-male-gruntyelling-sounds:3grunt1', 'grunt,effort,male', max=0.8)
S('grunt_effort_2', 'voice', 'oga-male-gruntyelling-sounds:3grunt4', 'grunt,effort,male', max=0.8)
S('announcer_fight', 'voice', 'kenney-voiceover-pack-fighter:/fight\.ogg', 'announcer,fight,start', max=1.4)
S('announcer_ready', 'voice', 'kenney-voiceover-pack-fighter:/ready\.ogg', 'announcer,ready', max=1.2)
S('announcer_winner', 'voice', 'kenney-voiceover-pack-fighter:/winner\.ogg', 'announcer,winner,victory', max=1.4)

# ---------------------------------------------------------------- crowd
S('crowd_cheer_1', 'crowd', 'oga-free-crowd-cheering-sounds:04 - Strong cheering - II', 'crowd,cheer', core=True, t0=1.5, read=4.0, max=2.8, fin=0.25, fout=0.5)
S('crowd_cheer_2', 'crowd', 'oga-cheers-0:cheers_1', 'crowd,cheer', max=2.0)
S('crowd_cheer_3', 'crowd', 'oga-free-crowd-cheering-sounds:06 - Soft cheering - II', 'crowd,cheer,soft', t0=2.0, read=4.0, max=2.8, fin=0.25, fout=0.5)
S('crowd_roar_1', 'crowd', 'oga-free-crowd-cheering-sounds:01 - Strong cheering and strong rhythmic', 'crowd,roar,cheer,loud', t0=3.0, read=6.0, max=4.0, fin=0.3, fout=0.8)
S('crowd_roar_2', 'crowd', 'oga-free-crowd-cheering-sounds:03 - Strong cheering - I\.', 'crowd,roar,cheer,loud', t0=4.0, read=6.0, max=4.0, fin=0.3, fout=0.8)
S('crowd_chant_1', 'crowd', 'oga-free-crowd-cheering-sounds:08 - Rhythmic cheering', 'crowd,chant,rhythmic', t0=2.0, read=5.0, max=3.5, fin=0.2, fout=0.6)
S('applause_1', 'crowd', 'oga-applause-in-a-large-hall-or-church:applause', 'crowd,applause,clap', t0=1.0, read=5.0, max=3.0, fin=0.2, fout=0.7)

# ---------------------------------------------------------------- horn
S('war_horn_1', 'horn', 'oga-their-coming-generic-horn-sound:theircoming3_0', 'horn,war horn,signal', core=True, max=3.0, fout=0.3)
S('war_horn_2', 'horn', 'oga-scary-echoey-horn-esque-sound:Massive Horn', 'horn,war horn,deep,signal', t0=0.0, read=6.0, max=3.0, fout=0.4)
S('war_horn_3', 'horn', 'oga-their-coming-generic-horn-sound:/theircoming_0', 'horn,war horn,signal', t0=0.0, read=6.0, max=3.2, fout=0.4)

# ---------------------------------------------------------------- drum / gong
S('drum_boom_1', 'drum', 'oga-taiko-drums-seamless-loop:taiko', 'drum,taiko,boom,low', core=True, on=3, read=30, max=0.4, fout=0.12)
S('drum_boom_2', 'drum', 'oga-taiko-drums-seamless-loop:taiko', 'drum,taiko,boom,low', on=9, read=30, max=0.4, fout=0.12)
S('drum_boom_3', 'drum', 'oga-horde-war-drums-loop:horde', 'drum,war drum,boom', on=7, max=0.3, fout=0.1)
S('drum_boom_4', 'drum', 'oga-horde-war-drums-loop:horde', 'drum,war drum,boom', on=14, max=0.3, fout=0.1)
S('drum_boom_5', 'drum', K_IMP + r':impactWood_heavy_000', 'drum,war drum,boom,low', rate=0.62, lp=900, max=1.0, notes='derived: pitched-down wood thud')
S('drum_boom_6', 'drum', K_IMP + r':impactPlate_heavy_001', 'drum,war drum,boom,low', rate=0.55, lp=700, max=1.1, notes='derived: pitched-down plate thud')
S('gong_1', 'drum', 'oga-100-cc0-sfx:gong_01', 'gong,metal,ring', max=2.0, fout=0.4)
S('gong_2', 'drum', 'oga-100-cc0-sfx:gong_02', 'gong,metal,ring', max=2.0, fout=0.4)
S('gong_3', 'drum', 'oga-gonk-gong:gong\.wav', 'gong,metal,ring', max=1.4, fout=0.3)

# ---------------------------------------------------------------- animals
S('horse_neigh_1', 'animal', 'commons-wiehern:Wiehern', 'horse,neigh,whinny', core=False, max=2.4, fout=0.2)
S('horse_gallop_1', 'animal', 'oga-horse-gallop-loop:gallop_01', 'horse,gallop,hooves', max=2.5, fout=0.2, t0=0.2)
S('hoof_step_1', 'animal', 'oga-horse-gallop-on-different-surfaces:/ground\.mp3', 'horse,hoof,step', max=0.7)
S('hoof_step_2', 'animal', 'oga-horse-gallop-on-different-surfaces:/grass\.mp3', 'horse,hoof,step', max=0.7)
S('elephant_trumpet_1', 'animal', 'commons-elephant-voice-trumpeting:Elephant', 'elephant,trumpet', max=1.8)
S('chicken_cluck_1', 'animal', 'oga-chicken-sound-effect:Chicken Sound Effect', 'chicken,cluck,comedy', core=True, seg=0, max=1.5)
S('chicken_cluck_2', 'animal', 'oga-chicken-sound-effect:Chicken Sound Effect', 'chicken,cluck,comedy', seg=1, max=1.5)
S('goat_bleat_1', 'animal', 'oga-goat-bleat:snom', 'goat,bleat,comedy', core=True, max=1.6)
S('camel_groan_1', 'animal', 'oga-camel-groan:camel_01', 'camel,groan', max=2.4, fout=0.3)
S('donkey_bray_1', 'animal', 'oga-donkey-bray:donkey', 'donkey,bray,comedy', max=1.9, fout=0.2)
S('sheep_baa_1', 'animal', 'oga-sheep-baa:sheep_baa', 'sheep,baa,comedy', max=1.0)
S('dog_bark_1', 'animal', 'oga-dog-sounds:Dog Bark 1', 'dog,bark', max=0.6)
S('dog_bark_2', 'animal', 'oga-dog-sounds:/Dog Bark 2', 'dog,bark', max=0.6)
S('wolf_howl_1', 'animal', 'oga-wolf-monster-sound:wolf', 'wolf,howl,growl', max=1.8, fout=0.3)
S('lion_roar_1', 'animal', 'commons-lion-raring-sound1tamilnadu178:Lion', 'lion,roar,beast', t0=0.3, read=3.0, max=2.2, fout=0.4, fin=0.02)
S('monster_roar_1', 'animal', CRE1 + r':roar_02', 'monster,roar,minotaur,cyclops,sphinx', max=1.6, fout=0.2)
S('monster_roar_2', 'animal', CRE2 + r':roar_05', 'monster,roar,minotaur,cyclops', max=1.6, fout=0.2)
S('monster_roar_4', 'animal', 'oga-cc0-deep-monster-roar:monster_roar', 'monster,roar,deep,giant', max=2.5, fout=0.4, on=0)
S('bear_roar_1', 'animal', 'commons-yellowstone-sound-library-grizzly-bears-roar-001:Roar', 'bear,roar,beast', t0=5.0, read=3.0, max=2.4, fout=0.4, hp=90)
S('snake_hiss_1', 'animal', 'commons-rattlesnake:Rattlesnake', 'snake,hiss,rattle', max=1.8, fout=0.3)
S('minotaur_grunt_1', 'animal', 'oga-osare-minotaur-sounds:mino', 'minotaur,grunt,growl', max=1.8)

# ---------------------------------------------------------------- siege
S('catapult_creak_1', 'siege', 'oga-tree-creaking:tree_creak', 'catapult,creak,wood,rope', max=2.0, fout=0.3)
S('catapult_creak_2', 'siege', K_RPG + r':creak2', 'catapult,creak,wood', max=1.6, fout=0.3)
S('catapult_launch_1', 'siege', '', 'catapult,launch,thwump', core=True, notes='composite: low wood thwump + short flight whoosh',
  layers=[(K_IMP + r':impactWood_heavy_001', 0.0, 0.0, dict(lp=900, pk=True)), ('oga-swish-bamboo-stick-weapon-swhoshes:swosh-33', 0.10, -4.0, dict(lp=5000, pk=True)), (K_IMP + r':impactWood_medium_002', 0.0, -6.0, dict(lp=2500, pk=True))], max=1.4, fout=0.25)
S('catapult_launch_2', 'siege', '', 'trebuchet,launch,thwump', notes='composite: heavy thud + slower whoosh',
  layers=[(K_IMP + r':impactWood_heavy_003', 0.0, 0.0, dict(lp=700, pk=True)), ('oga-swish-bamboo-stick-weapon-swhoshes:swosh-38', 0.16, -5.0, dict(lp=4000, pk=True)), (K_IMP + r':impactPlate_heavy_002', 0.0, -8.0, dict(lp=600, pk=True))], max=1.6, fout=0.25)
S('ballista_twang_1', 'siege', '', 'ballista,twang,bow', notes='composite: crossbow shoot + heavy wood knock',
  layers=[(MWT + r':Crossbow Shoot', 0.0, 0.0, dict()), (K_IMP + r':impactWood_heavy_000', 0.01, -5.0, dict(lp=1200))], max=1.4)
S('boulder_whoosh_1', 'siege', 'oga-swish-bamboo-stick-weapon-swhoshes:swosh-41', 'boulder,whoosh,flyby', peak=0, pre=0.6, post=0.7, max=1.3, lp=3500, rate=0.85)
S('boulder_impact_1', 'siege', 'oga-moving-boulder:boulder_drop', 'boulder,impact,thud,rock', core=True, max=2.0, fout=0.25)
S('boulder_impact_2', 'siege', 'oga-battle-at-sea:cannon_hit_wall_no_splash', 'boulder,impact,wall,crash', max=1.8, fout=0.3)
S('boulder_impact_3', 'siege', BRK + r':bfh1_rock_hit_01', 'boulder,impact,rock', max=1.6, fout=0.25)
S('boulder_impact_4', 'siege', 'oga-cave-in:cave_in', 'boulder,impact,rumble,rock', max=2.0, fout=0.4)

# ---------------------------------------------------------------- destruction
S('explosion_rumble_1', 'destruction', 'oga-chunky-explosion:Chunky', 'explosion,rumble,boom', max=2.4, fout=0.5)
S('explosion_rumble_2', 'destruction', 'oga-muffled-distant-explosion:Muffled', 'explosion,rumble,distant', max=2.4, fout=0.5)
S('explosion_rumble_4', 'destruction', 'commons-explosion-10:Explosion', 'explosion,boom', max=2.2, fout=0.5)
S('explosion_rumble_5', 'destruction', 'commons-explosion-ls100155:Explosion', 'explosion,boom,heavy', max=2.2, fout=0.5)
S('rock_crumble_1', 'destruction', BRK + r':bfh1_rock_breaking_01', 'rock,crumble,stone,break', max=1.8, fout=0.3)
S('rock_crumble_2', 'destruction', BRK + r':bfh1_rock_breaking_03', 'rock,crumble,stone,break', max=1.8, fout=0.3)
S('rock_crumble_3', 'destruction', 'oga-breaking-rock:rock_break', 'rock,crumble,stone,break', max=1.8, fout=0.3)
S('rock_fall_1', 'destruction', BRK + r':bfh1_rock_falling_04', 'rock,debris,fall,big', max=2.0, fout=0.3)
S('wood_crack_1', 'destruction', BRK + r':bfh1_wood_breaking_01', 'wood,crack,break', max=1.4)
S('wood_crack_2', 'destruction', BRK + r':bfh1_wood_breaking_03', 'wood,crack,break', max=1.4)
S('wood_crack_3', 'destruction', 'oga-35-wooden-crackshitsdestructions:crack03', 'wood,crack,splinter', max=1.6)
S('wood_splinter_1', 'destruction', 'oga-35-wooden-crackshitsdestructions:crack08', 'wood,splinter,crack', max=1.6)
S('wall_collapse_1', 'destruction', 'oga-cave-in:cave_in', 'wall,collapse,rubble,rumble', max=2.8, fout=0.6, t0=0.5)
S('debris_big_1', 'destruction', BRK + r':bfh1_falling_05', 'debris,big,fall,crash', max=2.0, fout=0.3)
S('voxel_break_1', 'destruction', 'oga-5-break-crunch-impacts:impactcrunch01', 'voxel,block,break,crunch', max=0.9)
S('voxel_break_2', 'destruction', 'oga-5-break-crunch-impacts:impactcrunch03', 'voxel,block,break,crunch', max=0.9)
S('voxel_break_3', 'destruction', K_IMP + r':impactMining_001', 'voxel,block,break,mining', max=0.8)

# ---------------------------------------------------------------- fire
S('fire_whoosh_1', 'fire', RPG80 + r':spell_fire_03', 'fire,whoosh,flame', max=1.6, fout=0.3)
S('fire_whoosh_2', 'fire', RPG80 + r':spell_fire_05', 'fire,whoosh,flame', max=1.6, fout=0.3)
S('fire_ignite_1', 'fire', 'oga-catching-fire:flame', 'fire,ignite,flame', max=1.8, fout=0.3)
S('torch_crackle_1', 'fire', 'oga-fire-crackling:fire-1', 'fire,torch,crackle', max=2.4, t0=1.0, fin=0.1, fout=0.4)

# ---------------------------------------------------------------- magic / lightning
S('heal_chime_1', 'magic', 'oga-cure-magic:Cure2', 'heal,chime,sparkle', max=1.8, fout=0.3)
S('heal_chime_2', 'magic', 'oga-cure-magic:Cure5', 'heal,chime,sparkle', max=1.8, fout=0.3)
S('buff_powerup_1', 'magic', 'oga-power-up-sound-effects:power_up_sound_v1', 'buff,powerup', max=1.4, fout=0.2)
S('buff_powerup_2', 'magic', 'oga-power-up-sound-effects:power_up_sound_v3', 'buff,powerup', max=1.4, fout=0.2)
S('buff_powerup_3', 'magic', 'oga-8-heals-and-buffs-sfx:16_Atk_buff', 'buff,attack,powerup', max=1.6, fout=0.3)
S('curse_dark_1', 'magic', 'oga-8-heals-and-buffs-sfx:21_Debuff', 'curse,dark,debuff', max=1.8, fout=0.3)
S('curse_dark_2', 'magic', 'oga-8-magic-attacks:46_Poison', 'curse,dark,poison,whoosh', max=1.8, fout=0.3)
S('magic_cast_1', 'magic', 'oga-8-magic-attacks:45_Charge', 'magic,cast,charge', max=1.8, fout=0.3)
S('thunder_crack_1', 'magic', 'oga-8-magic-attacks:18_Thunder', 'thunder,lightning,zeus', max=1.8, fout=0.3)
S('thunder_crack_2', 'magic', 'oga-100-cc0-sfx-2:sfx100v2_thunder_01', 'thunder,lightning,zeus', max=2.4, fout=0.5, start_db=-22)
S('lightning_zap_1', 'magic', 'oga-electricity-sound-effects-0:/spark\\.wav', 'lightning,zap,spark', max=1.0)

# ---------------------------------------------------------------- coin / bell
S('coin_pickup_1', 'coin', 'oga-plingy-coin:coin', 'coin,pickup,pling', max=0.8)
S('coin_pickup_2', 'coin', 'oga-gold-coin-6:coin', 'coin,pickup', max=0.8)
S('coin_clink_1', 'coin', K_RPG + r':handleCoins\.ogg', 'coin,clink', max=0.9)
S('coin_clink_2', 'coin', K_RPG + r':handleCoins2', 'coin,clink', max=1.0)
S('coin_sack_1', 'coin', 'oga-sack-of-gold:gold_sack', 'coin,sack,gold', max=1.4)
S('bell_ding_1', 'coin', 'oga-bell-dingschimes:bell_ding1', 'bell,ding', max=1.6, fout=0.3)
S('bell_heavy_1', 'coin', K_IMP + r':impactBell_heavy_001', 'bell,toll,heavy', max=2.0, fout=0.4)

# ---------------------------------------------------------------- foley
S('footstep_dirt_1', 'foley', 'oga-different-steps-on-wood-stone-leaves-gravel-and-mud:mud02', 'footstep,dirt,mud', max=0.5)
S('footstep_dirt_2', 'foley', 'oga-fantozzis-footsteps-grasssand-stone:SandL2', 'footstep,dirt,sand', max=0.5)
S('footstep_gravel_1', 'foley', 'oga-different-steps-on-wood-stone-leaves-gravel-and-mud:gravel', 'footstep,gravel', max=0.6)
S('footstep_gravel_2', 'foley', 'oga-different-steps-on-wood-stone-leaves-gravel-and-mud:stone01', 'footstep,stone,gravel', max=0.5)
S('footstep_grass_1', 'foley', K_IMP + r':footstep_grass_000', 'footstep,grass', max=0.5)
S('footstep_grass_2', 'foley', K_IMP + r':footstep_grass_002', 'footstep,grass', max=0.5)
S('footstep_grass_3', 'foley', K_IMP + r':footstep_grass_004', 'footstep,grass', max=0.5)
S('armor_rustle_1', 'foley', RPG80 + r':chain_01', 'armor,chainmail,rustle', max=1.0)
S('armor_rustle_2', 'foley', RPG80 + r':chain_02', 'armor,chainmail,rustle', max=1.0)
S('cloth_flap_1', 'foley', K_RPG + r':cloth1', 'cloth,flap,banner', max=0.9)
S('cloth_flap_2', 'foley', K_RPG + r':cloth3', 'cloth,flap,banner', max=0.9)
S('whoosh_camera_1', 'foley', 'oga-air-whoosh:whoosh2', 'whoosh,camera,air', max=0.9)
S('pop_place_1', 'foley', 'oga-pop-sounds:pop1\.', 'pop,place,unit', core=False, max=0.5)
S('pop_place_2', 'foley', 'oga-pop-sounds:pop4\.', 'pop,place,unit', max=0.5)
S('confetti_pop_1', 'foley', 'oga-balloon-sounds:balloon_pop', 'pop,confetti,celebrate', max=0.8)
S('splat_1', 'foley', 'oga-squish-sounds-effects:squish_02', 'splat,squish,comic', max=0.9)

# ---------------------------------------------------------------- UI
S('ui_hover_1', 'ui', K_UI + r':rollover1', 'ui,hover', core=True, max=0.4)
S('ui_hover_2', 'ui', K_UI + r':rollover3', 'ui,hover', max=0.4)
S('ui_click_1', 'ui', K_UI + r':/click2', 'ui,click', core=True, max=0.4)
S('ui_click_2', 'ui', K_INT + r':click_003', 'ui,click', max=0.4)
S('ui_confirm_1', 'ui', K_INT + r':confirmation_001', 'ui,confirm', core=True, max=0.8)
S('ui_confirm_2', 'ui', K_INT + r':confirmation_003', 'ui,confirm', max=0.8)
S('ui_back_1', 'ui', K_INT + r':back_001', 'ui,back,cancel', core=True, max=0.6)
S('ui_back_2', 'ui', K_INT + r':back_003', 'ui,back,cancel', max=0.6)
S('ui_error_1', 'ui', K_INT + r':error_001', 'ui,error,deny', max=0.7)
S('ui_error_2', 'ui', K_INT + r':error_005', 'ui,error,deny', max=0.7)
S('ui_toggle_on', 'ui', K_INT + r':toggle_001', 'ui,toggle,on', max=0.4)
S('ui_slider_tick', 'ui', K_INT + r':tick_002', 'ui,slider,tick', max=0.2)
S('ui_select_1', 'ui', K_INT + r':select_003', 'ui,select', max=0.5)
S('ui_panel_open', 'ui', K_INT + r':open_001', 'ui,panel,open', max=0.6)
S('ui_panel_close', 'ui', K_INT + r':close_001', 'ui,panel,close', max=0.6)
S('ui_drop_1', 'ui', K_INT + r':drop_002', 'ui,drop,place', max=0.5)
S('ui_achievement_1', 'ui', 'oga-achievement:achievement', 'ui,achievement,jingle', max=2.4, fout=0.5)
S('ui_achievement_2', 'ui', 'oga-chimey-ui-sounds:Chime_LevelUp', 'ui,achievement,levelup', max=2.0, fout=0.4)
S('ui_achievement_3', 'ui', 'oga-7-assorted-sound-effects-menu-level-up:Level Up', 'ui,achievement,levelup', max=2.0, fout=0.4)
S('countdown_beep', 'ui', 'synth:beep', 'countdown,beep,3,2,1', freq=660.0, dur=0.22, notes='synthesized sine beep; play once each for 3, 2, 1')
S('countdown_go', 'ui', 'synth:beep', 'countdown,beep,go', freq=1320.0, dur=0.7, decay=0.8, notes='synthesized sine beep (higher pitch, longer)')
S('countdown_voice_3', 'ui', 'kenney-voiceover-pack:/3\\.ogg', 'countdown,voice,3', max=0.8)
S('countdown_voice_2', 'ui', 'kenney-voiceover-pack:/2\\.ogg', 'countdown,voice,2', max=0.8)
S('countdown_voice_1', 'ui', 'kenney-voiceover-pack:/1\\.ogg', 'countdown,voice,1', max=0.8)
S('countdown_voice_go', 'ui', 'kenney-voiceover-pack:/go\\.ogg', 'countdown,voice,go', max=0.9)

# ---------------------------------------------------------------- jingles / stingers
S('jingle_victory_1', 'jingle', 'oga-win-jingle:WinBrass\\.ogg', 'jingle,victory,fanfare,brass', core=True, max=4.0, fout=0.5)
S('jingle_victory_2', 'jingle', 'oga-win-jingle:WinStrings\\.ogg', 'jingle,victory,strings', max=4.0, fout=0.5)
S('jingle_victory_3', 'jingle', 'oga-won-orchestral-winning-jingle:Won', 'jingle,victory,orchestral', max=4.6, fout=0.6)
S('jingle_victory_4', 'jingle', 'oga-classic-fanfare-lick:fanfare_3', 'jingle,victory,fanfare', max=3.0, fout=0.4)
S('jingle_fanfare_1', 'jingle', 'oga-hyper-ultra-fanfare:sboe', 'jingle,fanfare,battle start', max=4.0, fout=0.6)
S('jingle_battle_start_1', 'jingle', 'oga-orchestral-stinger-dramatic-entrance:orchestral_stinger_dramatic_entrance\\.wav', 'jingle,stinger,battle start,drama', max=3.6, fout=0.7)
S('jingle_battle_start_2', 'jingle', '', 'jingle,fanfare,battle start,horn,drum', notes='composite: war horn + taiko boom + gong',
  layers=[('oga-their-coming-generic-horn-sound:theircoming3_0', 0.0, -2.0, dict(dur=3.0)), ('oga-horde-war-drums-loop:horde', 0.0, -3.0, dict(dur=0.5)), ('oga-100-cc0-sfx:gong_01', 0.02, -8.0, dict())], max=3.2, fout=0.6)
S('jingle_defeat_1', 'jingle', 'oga-game-over-trumpet-sfx:losetrumpet\\.wav', 'jingle,defeat,sting,trumpet', core=True, max=2.0, fout=0.3)
S('jingle_defeat_2', 'jingle', 'oga-kl-peach-game-over-iii:Game Over III\\.wav', 'jingle,defeat,sting', max=3.7, fout=0.6)
S('jingle_achievement_1', 'jingle', 'oga-win-sound-effect:Win sound', 'jingle,achievement,win', max=3.0, fout=0.5)

# ---------------------------------------------------------------- ambience loops (cross-faded to loop)
S('ambience_wind_loop', 'ambience', 'oga-wind1:wind2', 'ambience,wind,loop', t0=10, read=7, max=5.5, xfade=0.8, nolimit=True)
S('ambience_crowd_loop', 'ambience', 'oga-free-crowd-cheering-sounds:10 - Ambience', 'ambience,crowd,loop,murmur', t0=6, read=7, max=5.5, xfade=0.8, nolimit=True)
S('ambience_fire_loop', 'ambience', 'oga-fireplace-sound-loop:fire', 'ambience,fire,loop,crackle', t0=0.5, read=6, max=4.5, xfade=0.7, nolimit=True)

# ---------------------------------------------------------------- Wikimedia Commons additions
S('horse_neigh_2', 'animal', 'commons-mares-prefer-the-voices-of-highly-fertile-stallions-pone-0118468-s001:', 'horse,neigh,whinny', max=2.2, fout=0.25, notes='scientific recording of a horse vocalisation')
S('horse_neigh_3', 'animal', 'commons-mares-prefer-the-voices-of-highly-fertile-stallions-pone-0118468-s003:', 'horse,neigh,whinny', max=2.6, fout=0.3, notes='scientific recording of a horse vocalisation')
S('drum_roll_1', 'drum', 'commons-drum-roll-intro:Drum', 'drum,roll,snare', max=2.8, fout=0.35)

# ---------------------------------------------------------------- extras
GQ = 'oga-free-cinematic-sound-effects'
S('rock_crumble_4', 'destruction', GQ + r':Rocks - Elements 09', 'rock,crumble,stone,debris', max=2.2, fout=0.4)

# ---------------------------------------------------------------- Wikimedia Commons (rate-limited download; entries are skipped by the manifest if the file could not be fetched)
S('crowd_ooh_2', 'crowd', 'commons-ohhh-ahhh:Ohhh', 'crowd,gasp,ooh,aww', max=2.2, fout=0.4, fin=0.05)
S('crowd_hurray_1', 'crowd', 'commons-hurray:Hurray', 'crowd,cheer,hurray', max=2.2, fout=0.3)
S('crowd_cheer_4', 'crowd', 'commons-clapping-hurray:Clapping', 'crowd,cheer,clap', max=3.0, fout=0.5)
S('crowd_boo_1', 'crowd', 'commons-soundgoats-audience-booing:Booing', 'crowd,boo,disapproval', max=2.6, fout=0.5, fin=0.1)
S('war_horn_4', 'horn', 'commons-hunting-horn-tone:Hunting', 'horn,hunting horn,signal', t0=0.0, read=5.0, max=2.5, fout=0.35)
S('war_horn_5', 'horn', 'commons-blumlisalp-horn:Horn', 'horn,alphorn,deep,signal', max=1.9, fout=0.3)
S('bugle_call_1', 'horn', 'commons-assembly-bugle-call:Assembly', 'bugle,trumpet,signal,call', max=3.0, fout=0.4)
S('bugle_call_2', 'horn', 'commons-attention-bugle-call-us:Attention', 'bugle,trumpet,signal,call', max=3.0, fout=0.4)
S('drum_boom_7', 'drum', 'commons-02-taiko2-short:Taiko', 'drum,taiko,boom,low', on=0, max=1.2, fout=0.25)
S('drum_boom_8', 'drum', 'commons-02-taiko2-short:Taiko', 'drum,taiko,boom,low', on='strongest', max=1.2, fout=0.25)
S('timpani_hit_1', 'drum', 'commons-timpani-64-c-p5:Timpani', 'drum,timpani,boom,low', max=1.6, fout=0.3)
S('gong_4', 'drum', 'commons-gong55:Gong', 'gong,metal,ring', max=2.4, fout=0.5)
S('gong_5', 'drum', 'commons-gong-or-bell-vibrant-short:Gong', 'gong,bell,metal,ring', max=2.2, fout=0.4)
S('chicken_cluck_5', 'animal', 'commons-chicken-in-vezo:Chicken', 'chicken,cluck,comedy', max=1.2)
S('chicken_cluck_6', 'animal', 'commons-chicken-in-antefasy:Chicken', 'chicken,cluck,comedy', max=1.5)
S('goat_bleat_4', 'animal', 'commons-goat-in-antefasy:Goat', 'goat,bleat,comedy', max=1.7)
S('sheep_baa_3', 'animal', 'commons-sheep-bleat:Sheep', 'sheep,baa,comedy', max=0.8)
S('wolf_howl_2', 'animal', 'commons-wolf-howls:Wolf', 'wolf,howl', seg=0, thr=-30, max=2.4, fout=0.4)
S('death_hurt_3', 'death', 'commons-male-pain-grunts:Male', 'hurt,pain,grunt,male', seg=1, thr=-30, max=0.9)
S('death_hurt_4', 'death', 'commons-male-pain-grunts:Male', 'hurt,pain,grunt,male', seg=3, thr=-30, max=0.9)
S('death_grunt_7', 'death', 'commons-male-grunts-jumps:Male', 'death,grunt,male,oof', seg=2, thr=-30, max=0.9)
S('death_scream_5', 'death', 'commons-now-screaming:NOW', 'death,scream,comic', max=1.8, fout=0.3)
S('death_oof_3', 'death', 'commons-grunt-of-pain:Grunt', 'death,oof,grunt,male', max=0.6)
S('thunder_crack_4', 'magic', 'commons-nosferatu-thunderclap-richard-humphries:Nosferatu', 'thunder,lightning,zeus', max=2.6, fout=0.6, start_db=-26)
S('thunder_rumble_1', 'magic', 'commons-thunder-and-rain-on-a-v:Thunder', 'thunder,rumble,rain', t0=3.0, read=8.0, max=2.6, fout=0.6, start_db=-26)
S('explosion_rumble_6', 'destruction', 'commons-explosions-ls100152:Explosions', 'explosion,boom,heavy', max=2.4, fout=0.5)
S('spear_stab_1', 'pierce', 'commons-stab-damage-gravity-sound:Stab', 'spear,stab,flesh', max=1.0)
S('spear_stab_2', 'pierce', 'commons-stab-damage-monster-gravity-sound:Stab', 'spear,stab,flesh,monster', max=1.0)
S('flesh_hit_heavy_4', 'impact', 'commons-hard-punch-flesh-gravity-sound:Punch', 'flesh,hit,heavy,punch', max=1.0)
S('flesh_hit_heavy_5', 'impact', 'commons-hard-punch-gut-gravity-sound:Punch', 'flesh,hit,heavy,gut', max=1.0)
S('flesh_hit_light_6', 'impact', 'commons-punch-flesh-damage-gravity-sound:Punch', 'flesh,hit,light,punch', max=0.9)
S('blade_clash_7', 'blade', 'commons-sword-clash-gravity-sound:Sword Clash', 'metal,clash,parry,sword', max=1.2)
S('blade_clash_8', 'blade', 'commons-sword-clash-3-gravity-sound:Sword Clash', 'metal,clash,parry,sword', max=1.2)
S('sword_slash_5', 'blade', 'commons-sword-swipe-gravity-sound:Sword Swipe', 'sword,slash,swing,whoosh', max=0.6)
S('sword_hit_6', 'blade', 'commons-sword-1-gravity-sound:Sword', 'sword,hit,slash', max=1.0)
S('sword_hit_7', 'blade', 'commons-sword-6-gravity-sound:Sword', 'sword,hit,slash', max=1.0)
S('creature_swipe_1', 'blade', 'commons-swipe-monster-gravity-sound:Swipe', 'claw,swipe,monster,whoosh', max=1.0)
S('footstep_gravel_4', 'foley', 'commons-footstep-on-gravel-gravity-sound:Footstep', 'footstep,gravel', max=0.6)


# ---------------------------------------------------------------- restored variants + extra variants so every game cue family has >=3 options
S('sword_hit_5', 'blade', SW + r':/sword\.4\.ogg', 'sword,hit,slash', max=1.2)
S('blade_clash_6', 'blade', VEH + r':sword-knife-clash-22', 'metal,clash,parry', max=1.2)
S('blade_parry_3', 'blade', MWI + r':Dagger Katana Blade on Blade', 'metal,parry,ring', on=0, max=1.4)
S('blade_swish_3', 'blade', 'oga-swish-bamboo-stick-weapon-swhoshes:swosh-20', 'whoosh,swing,weapon', max=0.9)
S('knife_slice_2', 'blade', K_RPG + r':knifeSlice2', 'knife,slice', max=0.8)
S('shield_bash_3', 'shield', K_IMP + r':impactPlate_medium_001', 'shield,bash,metal', max=1.0)
S('wood_thud_4', 'shield', BRK + r':bfh1_wood_hit_02', 'wood,thud', max=1.0)
S('bow_shot_3', 'bow', 'oga-battle-sound-effects:Bow\.wav', 'bow,arrow,shoot', max=0.8)
S('arrow_hit_wood_3', 'bow', BRK + r':bfh1_wood_hit_01', 'arrow,hit,wood', max=0.7)
S('arrow_hit_flesh_3', 'bow', K_IMP + r':impactSoft_heavy_003', 'arrow,hit,flesh', max=0.8)
S('arrow_hit_flesh_4', 'bow', K_IMP + r':impactSoft_medium_000', 'arrow,hit,flesh', max=0.8)
S('flesh_hit_light_5', 'impact', 'oga-37-hitspunches:hit25', 'flesh,hit,light', max=0.9)
S('death_grunt_6', 'death', 'oga-male-dead-voice:enemy_dead_10', 'death,grunt,male', max=1.0)
S('death_scream_3', 'death', 'oga-aargh-male-screams:aargh1', 'death,scream,male', max=1.2)
S('death_scream_4', 'death', 'oga-aargh-male-screams:aargh7', 'death,scream,male', max=1.3)
S('death_dying_3', 'death', 'oga-11-male-human-paindeath-sounds:deathh', 'death,dying,male', max=1.2)
S('death_hurt_2', 'death', 'oga-11-male-human-paindeath-sounds:pain5', 'hurt,pain,male', max=0.9)
S('battle_cry_6', 'voice', 'oga-tiny-creatures-sounds:battlecry1', 'battle cry,comic,tiny', max=0.9)
S('war_cry_3', 'voice', 'oga-steampunk-fantasy-voices:Pikeman_Attack_001', 'war cry,pike,attack', max=1.2)
S('war_cry_4', 'voice', 'oga-steampunk-fantasy-voices:Guard_Attack_001', 'war cry,guard,attack', max=1.0)
S('war_cry_5', 'voice', 'oga-steampunk-fantasy-voices:Knight_Attack_002', 'war cry,knight,attack', max=1.0)
S('orc_roar_1', 'voice', 'oga-orc-voice:/ORC FIGHT\.wav', 'roar,orc,war cry', max=1.0)
S('grunt_effort_3', 'voice', 'oga-male-gruntyelling-sounds:3grunt6', 'grunt,effort,male', max=1.0)
S('announcer_flawless', 'voice', 'kenney-voiceover-pack-fighter:flawless_victory', 'announcer,flawless,victory', max=2.0)
S('announcer_winner_2', 'voice', 'kenney-voiceover-pack-fighter:/you_win\.ogg', 'announcer,winner,victory', max=1.2)
S('announcer_winner_3', 'voice', 'kenney-voiceover-pack:/you_win\.ogg', 'announcer,winner,victory', max=1.2)
S('announcer_ready_2', 'voice', 'kenney-voiceover-pack:/ready\.ogg', 'announcer,ready', max=1.0)
S('announcer_ready_3', 'voice', 'kenney-voiceover-pack-fighter:prepare_yourself', 'announcer,ready,prepare', max=1.6)
S('announcer_fight_2', 'voice', 'kenney-voiceover-pack-fighter:/begin\.ogg', 'announcer,fight,start', max=1.2)
S('announcer_fight_3', 'voice', 'kenney-voiceover-pack:/set\.ogg', 'announcer,set,start', max=0.9)
S('footstep_gravel_3', 'foley', 'oga-fantozzis-footsteps-grasssand-stone:StoneL1', 'footstep,stone,gravel', max=0.5)
S('footstep_gravel_5', 'foley', 'oga-fantozzis-footsteps-grasssand-stone:StoneR2', 'footstep,stone,gravel', max=0.5)
S('footstep_dirt_3', 'foley', 'oga-fantozzis-footsteps-grasssand-stone:SandR3', 'footstep,dirt,sand', max=0.5)
S('footstep_dirt_4', 'foley', 'oga-different-steps-on-wood-stone-leaves-gravel-and-mud:leaves01', 'footstep,dirt,leaves', max=0.6)
S('footstep_sand_1', 'foley', 'oga-fantozzis-footsteps-grasssand-stone:SandL1', 'footstep,sand', max=0.5)
S('footstep_sand_2', 'foley', 'oga-fantozzis-footsteps-grasssand-stone:SandR1', 'footstep,sand', max=0.5)
S('footstep_sand_3', 'foley', 'oga-fantozzis-footsteps-grasssand-stone:SandL3', 'footstep,sand', max=0.5)
S('footstep_mud_1', 'foley', 'oga-different-steps-on-wood-stone-leaves-gravel-and-mud:mud02', 'footstep,mud', max=0.5)
S('footstep_mud_2', 'foley', 'oga-fantasy-sound-effects-tinysized-sfx:mud-steps-03', 'footstep,mud', max=0.6)
S('footstep_mud_3', 'foley', 'oga-fantasy-sound-effects-tinysized-sfx:mud-steps-05', 'footstep,mud', max=0.6)
S('footstep_wood_1', 'foley', 'oga-different-steps-on-wood-stone-leaves-gravel-and-mud:wood01', 'footstep,wood', max=0.5)
S('footstep_wood_2', 'foley', 'oga-different-steps-on-wood-stone-leaves-gravel-and-mud:wood02', 'footstep,wood', max=0.5)
S('footstep_wood_3', 'foley', 'oga-different-steps-on-wood-stone-leaves-gravel-and-mud:wood03', 'footstep,wood', max=0.5)
S('footstep_snow_1', 'foley', K_IMP + r':footstep_snow_000', 'footstep,snow', max=0.5)
S('footstep_snow_2', 'foley', K_IMP + r':footstep_snow_002', 'footstep,snow', max=0.5)
S('footstep_snow_3', 'foley', K_IMP + r':footstep_snow_004', 'footstep,snow', max=0.5)
S('footstep_water_1', 'foley', 'oga-100-cc0-sfx-2:sfx100v2_footstep_wet_01', 'footstep,water,wet', max=0.6)
S('footstep_water_2', 'foley', 'oga-100-cc0-sfx-2:sfx100v2_footstep_wet_02', 'footstep,water,wet', max=0.6)
S('footstep_water_3', 'foley', 'oga-100-cc0-sfx-2:sfx100v2_footstep_wet_03', 'footstep,water,wet', max=0.6)
S('armor_rustle_3', 'foley', RPG80 + r':chain_03', 'armor,chainmail,rustle', max=1.0)
S('armor_step_1', 'foley', 'oga-footsteps-leather-cloth-armor:step_metal\.', 'armor,step,metal', max=0.6)
S('armor_step_2', 'foley', 'oga-footsteps-leather-cloth-armor:step_metal \(2\)', 'armor,step,metal', max=0.6)
S('armor_step_3', 'foley', 'oga-footsteps-leather-cloth-armor:step_metal \(3\)', 'armor,step,metal', max=0.6)
S('cloth_flap_3', 'foley', K_RPG + r':clothBelt\.ogg', 'cloth,belt,rustle', max=0.9)
S('whoosh_camera_2', 'foley', 'oga-swish-bamboo-stick-weapon-swhoshes:swosh-03', 'whoosh,camera', max=0.9)
S('whoosh_camera_3', 'foley', 'oga-swish-bamboo-stick-weapon-swhoshes:swosh-12', 'whoosh,camera', max=0.8)
S('pop_place_3', 'foley', 'oga-pop-sounds:pop7\.', 'pop,place,unit', max=0.5)
S('pop_place_4', 'foley', 'oga-pop-sounds:pop2\.', 'pop,place,unit', max=0.5)
S('confetti_pop_2', 'foley', 'oga-25-cc0-bang-firework-sfx:bang_03', 'pop,confetti,celebrate', max=1.0)
S('confetti_pop_3', 'foley', 'oga-25-cc0-bang-firework-sfx:fw_02', 'pop,confetti,celebrate,firework', max=1.4, fout=0.25)
S('explosion_rumble_3', 'destruction', 'oga-explosion-0:explosion', 'explosion,boom', max=2.2, fout=0.5)
S('rock_fall_2', 'destruction', BRK + r':bfh1_rock_falling_08', 'rock,debris,fall,big', max=2.0, fout=0.3)
S('debris_big_2', 'destruction', BRK + r':bfh1_misc_03', 'debris,big,crash', max=2.0, fout=0.3)
S('voxel_break_4', 'destruction', K_IMP + r':impactMining_003', 'voxel,block,break,mining', max=0.8)
S('fire_ignite_2', 'fire', RPG80 + r':spell_fire_01', 'fire,ignite,flame', max=1.6, fout=0.3)
S('torch_crackle_2', 'fire', 'oga-fire-crackling:fire-1', 'fire,torch,crackle', t0=0.4, max=2.2, fin=0.1, fout=0.4, rate=0.92)
S('torch_crackle_3', 'fire', 'oga-fire-crackling:fire-1', 'fire,torch,crackle', t0=0.8, max=2.0, fin=0.1, fout=0.4, rate=1.08)
S('heal_chime_3', 'magic', 'oga-3-heal-spells:healspell2', 'heal,chime', max=1.8, fout=0.3)
S('heal_chime_4', 'magic', 'oga-cure-magic:Cure7', 'heal,chime,sparkle', max=1.8, fout=0.3)
S('curse_dark_3', 'magic', 'oga-8-heals-and-buffs-sfx:44_Sleep', 'curse,dark,sleep', max=1.8, fout=0.3)
S('curse_dark_4', 'magic', 'oga-8-heals-and-buffs-sfx:39_Absorb', 'curse,dark,absorb', max=1.8, fout=0.3)
S('thunder_crack_3', 'magic', 'oga-thunder:thunderclap', 'thunder,lightning,zeus', max=2.4, fout=0.5)
S('lightning_zap_2', 'magic', 'oga-electricity-sound-effects-0:continuousspark', 'lightning,zap,spark', rate=0.8, max=0.9, fout=0.2)
S('lightning_zap_3', 'magic', 'oga-electricity-sound-effects-0:continuousspark', 'lightning,zap,spark', rate=0.6, max=0.9, fout=0.2)
S('magic_cast_2', 'magic', 'oga-8-magic-attacks:30_Earth', 'freeze,stone,earth,magic', max=1.8, fout=0.3)
S('magic_cast_3', 'magic', 'oga-8-magic-attacks:13_Ice', 'freeze,ice,stone,magic', max=1.8, fout=0.3)
S('magic_cast_4', 'magic', 'oga-freeze-spell-0:freeze', 'freeze,ice,stone,magic', max=1.8, fout=0.3)
S('coin_pickup_3', 'coin', RPG80 + r':item_coins_02', 'coin,pickup', max=0.8)
S('bell_ding_2', 'coin', 'oga-bell-dingschimes:bell_ding3', 'bell,ding', max=1.6, fout=0.3)
S('ui_click_3', 'ui', K_UI + r':mouseclick1', 'ui,click,mouse', max=0.4)
S('ui_click_4', 'ui', K_UI + r':/click4', 'ui,click', max=0.4)
S('ui_hover_3', 'ui', K_UI + r':rollover5', 'ui,hover', max=0.4)
S('ui_confirm_3', 'ui', K_INT + r':confirmation_002', 'ui,confirm', max=0.8)
S('ui_back_3', 'ui', K_INT + r':back_004', 'ui,back,cancel', max=0.6)
S('ui_error_3', 'ui', K_INT + r':error_003', 'ui,error,deny', max=0.7)
S('ui_toggle_off', 'ui', K_INT + r':toggle_003', 'ui,toggle,off', max=0.4)
S('ui_toggle_on_2', 'ui', K_INT + r':toggle_002', 'ui,toggle,on', max=0.4)
S('ui_toggle_off_2', 'ui', K_INT + r':toggle_004', 'ui,toggle,off', max=0.4)
S('ui_slider_tick_2', 'ui', K_INT + r':tick_001', 'ui,slider,tick', max=0.2)
S('ui_select_2', 'ui', K_INT + r':select_005', 'ui,select', max=0.5)
S('ui_maximize', 'ui', K_INT + r':maximize_004', 'ui,panel,open,expand', max=0.6)
S('ui_minimize', 'ui', K_INT + r':minimize_004', 'ui,panel,close,collapse', max=0.6)
S('ui_panel_open_2', 'ui', K_INT + r':open_003', 'ui,panel,open', max=0.6)
S('ui_panel_close_2', 'ui', K_INT + r':close_003', 'ui,panel,close', max=0.6)
S('ui_notify_1', 'ui', 'oga-chimey-ui-sounds:Chime_Confirm', 'ui,notify,chime', max=1.2, fout=0.3)
S('countdown_beep_2', 'ui', 'synth:beep', 'countdown,beep,2', freq=740.0, dur=0.22, notes='synthesized sine beep')
S('countdown_beep_3', 'ui', 'synth:beep', 'countdown,beep,1', freq=830.0, dur=0.22, notes='synthesized sine beep')
S('countdown_go_2', 'ui', 'synth:beep', 'countdown,beep,go', freq=1480.0, dur=0.7, decay=0.8, notes='synthesized sine beep (variant)')
S('countdown_go_3', 'ui', 'synth:beep', 'countdown,beep,go', freq=1175.0, dur=0.7, decay=0.8, notes='synthesized sine beep (variant)')
S('spear_stab_4', 'pierce', K_RPG + r':drawKnife2', 'stab,knife', max=0.9)
S('spear_stab_5', 'pierce', K_RPG + r':drawKnife3', 'spear,stab,knife', max=0.9)
S('spear_swing_2', 'pierce', 'oga-swish-bamboo-stick-weapon-swhoshes:swosh-30', 'spear,thrust,swing,whoosh', peak=0, pre=0.35, post=0.4, max=0.75, hp=60)
S('spear_swing_3', 'pierce', 'oga-swish-bamboo-stick-weapon-swhoshes:swosh-33', 'spear,thrust,swing,whoosh', peak=0, pre=0.35, post=0.4, max=0.75, hp=60)
S('javelin_throw_3', 'pierce', 'oga-swish-bamboo-stick-weapon-swhoshes:swosh-29', 'javelin,throw,whoosh', peak=0, pre=0.4, post=0.4, max=0.8, hp=60)
S('axe_chop_3', 'blade', 'oga-chopping-tree:choppingtree', 'axe,chop,wood', on=0, max=0.8)
S('axe_chop_4', 'blade', 'oga-chopping-tree:choppingtree', 'axe,chop,wood', on=2, max=0.8)
S('camel_groan_2', 'animal', 'oga-fantasy-desert-ride-able-camel:camel', 'camel,groan', max=2.0, fout=0.3)
S('monster_roar_3', 'animal', RPG80 + r':creature_roar_03', 'monster,roar,minotaur,cyclops', max=1.6, fout=0.2)
S('catapult_creak_3', 'siege', K_RPG + r':creak3', 'trebuchet,creak,wood', max=1.6, fout=0.3)
S('catapult_creak_4', 'siege', 'oga-wood-wobbling-rattling:wobble1', 'catapult,creak,wood,rattle', max=0.9, fout=0.2)
S('catapult_launch_3', 'siege', '', 'catapult,launch,thwump', notes='composite: dull thwump + whoosh + wooden clack',
  layers=[(K_IMP + r':impactWood_heavy_004', 0.0, 0.0, dict(lp=800, pk=True)), ('oga-swish-bamboo-stick-weapon-swhoshes:swosh-30', 0.12, -4.0, dict(lp=4500, pk=True)), (K_IMP + r':impactWood_light_002', 0.03, -7.0, dict(pk=True))], max=1.3, fout=0.25)
S('boulder_whoosh_2', 'siege', 'oga-swish-bamboo-stick-weapon-swhoshes:swosh-38', 'boulder,whoosh,flyby', peak=0, pre=0.55, post=0.6, max=1.2, lp=3500, rate=0.75)
S('boulder_whoosh_3', 'siege', 'oga-swish-bamboo-stick-weapon-swhoshes:swosh-35', 'boulder,whoosh,flyby', peak=0, pre=0.6, post=0.7, max=1.3, lp=3000, rate=0.7)
S('elephant_trumpet_2', 'animal', 'commons-elephant-voice-trumpeting:Elephant', 'elephant,trumpet', rate=0.86, max=1.9, notes='pitch-shifted variant of the same recording')
S('elephant_trumpet_3', 'animal', 'commons-elephant-voice-trumpeting:Elephant', 'elephant,trumpet', rate=1.14, max=1.6, notes='pitch-shifted variant of the same recording')
S('snake_hiss_2', 'animal', 'commons-rattlesnake:Rattlesnake', 'snake,hiss,rattle', t0=4.0, max=1.6, fout=0.3, hp=300)
S('snake_hiss_3', 'animal', 'commons-rattlesnake:Rattlesnake', 'snake,hiss,rattle', t0=9.0, max=1.4, fout=0.3, rate=1.1)
S('dog_bark_3', 'animal', 'oga-dog-sounds:Dog Bark 3', 'dog,bark', max=0.6)
S('dog_bark_4', 'animal', 'oga-dog-sounds:/Dog Bark\.wav', 'dog,bark', on=0, max=0.6)
S('chicken_cluck_3', 'animal', 'oga-chicken-sound-effect:Chicken Sound Effect', 'chicken,cluck,comedy', seg=1, rate=1.06, max=1.5, notes='pitch-shifted variant')
S('chicken_cluck_4', 'animal', 'oga-chicken-sound-effect:Chicken Sound Effect', 'chicken,cluck,comedy', seg=0, rate=1.12, max=1.2, notes='pitch-shifted variant')
S('goat_bleat_2', 'animal', 'oga-goat-bleat:snom', 'goat,bleat,comedy', rate=0.85, max=1.9, notes='pitch-shifted variant')
S('goat_bleat_3', 'animal', 'oga-goat-bleat:snom', 'goat,bleat,comedy', rate=1.15, max=1.4, notes='pitch-shifted variant')
S('sheep_baa_2', 'animal', 'oga-sheep-baa:sheep_baa', 'sheep,baa,goat,comedy', rate=0.88, max=1.1, notes='pitch-shifted variant')
S('donkey_bray_2', 'animal', 'oga-donkey-bray:donkey', 'donkey,bray,comedy', rate=1.1, max=1.7, fout=0.2, notes='pitch-shifted variant')
S('drum_roll_2', 'drum', 'commons-drum-roll-intro:Drum', 'drum,roll,snare', rate=0.92, max=2.8, fout=0.35, notes='pitch-shifted variant of the same roll')
S('drum_roll_3', 'drum', 'commons-drum-roll-intro:Drum', 'drum,roll,snare', rate=1.1, max=2.4, fout=0.35, notes='pitch-shifted variant of the same roll')
S('jingle_defeat_3', 'jingle', 'oga-level-up-power-up-coin-get-13-sounds:Downer01', 'jingle,defeat,sting,down', max=2.0, fout=0.35)
S('stinger_funny_1', 'jingle', 'oga-boing:boing', 'stinger,funny,comic', max=1.2, fout=0.2)
S('stinger_funny_2', 'jingle', 'oga-silly-sound-effects:bloop', 'stinger,funny,comic', max=0.8)
S('stinger_funny_3', 'jingle', 'oga-slide-whistle-down:slide', 'stinger,funny,comic,slide whistle', max=1.5, fout=0.2)

S('ambience_wind_loop_2', 'ambience', 'oga-wind1:wind4', 'ambience,wind,loop', t0=14, read=7, max=5.5, xfade=0.8, nolimit=True)
S('ambience_crowd_loop_2', 'ambience', 'oga-free-crowd-cheering-sounds:09 - Ambience and cheering', 'ambience,crowd,loop,murmur', t0=8, read=7, max=5.5, xfade=0.8, nolimit=True)
S('ambience_fire_loop_2', 'ambience', 'oga-fire-crackling:fire-1_0', 'ambience,fire,loop,crackle', t0=0.2, read=3.4, max=3.0, xfade=0.5, nolimit=True)


# ---------------------------------------------------------------- availability filter
# Wikimedia Commons downloads are rate limited (HTTP 429 on upload.wikimedia.org); entries whose raw folder was not fetched are skipped,
# so the build stays reproducible. Re-run `tools/fetch_commons.py @tools/commons_wanted.txt` later and rebuild to add them.
import os as _os
def _raw_ok(s):
    o = s.get('opts', {})
    dirs = [l[0].split(':')[0] for l in o['layers']] if 'layers' in o else ([] if s['src'].startswith('synth:') else [s['src'].split(':')[0]])
    return all(_os.path.isdir(_os.path.join('/home/user/voxelwars/assets/raw', d)) for d in dirs)
SPEC[:] = [s for s in SPEC if _raw_ok(s)]

# ---------------------------------------------------------------- derived composites (no real recording available under an acceptable licence)
S('crowd_ooh_1', 'crowd', '', 'crowd,ooh,gasp,aww,reaction', notes='derived composite (approximation): four pitch-shifted copies of a creature "ooh" voice over a soft crowd murmur bed',
  layers=[(CRE1 + r':/ooh\.', 0.00, -2.0, dict(rate=0.66, lp=5000)), (CRE1 + r':/ooh\.', 0.035, -3.0, dict(rate=0.74, lp=5000)), (CRE1 + r':/ooh\.', 0.075, -3.0, dict(rate=0.82, lp=5000)), (CRE1 + r':/ooh\.', 0.12, -4.0, dict(rate=0.92, lp=5000)),
          ('oga-free-crowd-cheering-sounds:07 - Soft cheering and chatter', 0.0, -9.0, dict(t0=3.0, dur=1.6, norm=False))], max=1.4, fout=0.35)
S('crowd_gasp_1', 'crowd', '', 'crowd,gasp,inhale,reaction', notes='derived composite (approximation): five pitch-shifted creature breaths over a soft crowd murmur bed',
  layers=[(CRE1 + r':/breath\.', 0.00, -2.0, dict(rate=0.8)), (CRE1 + r':/breath\.', 0.03, -3.0, dict(rate=0.9)), (CRE1 + r':/breath\.', 0.07, -3.0, dict(rate=1.0)), (CRE1 + r':/breath\.', 0.10, -4.0, dict(rate=1.1)), (CRE1 + r':/breath\.', 0.15, -5.0, dict(rate=1.2)),
          ('oga-free-crowd-cheering-sounds:07 - Soft cheering and chatter', 0.0, -12.0, dict(t0=6.0, dur=1.4, norm=False))], max=1.2, fout=0.3)
